# Copyright (c) Meta Platforms, Inc. and affiliates.

load("@fbcode_macros//build_defs:python_library.bzl", "python_library")

oncall("data_compression")

python_library(
    # @autodeps-skip
    name = "openzl",
    srcs = glob(["src/**/*.py"]),
    base_module = "",
    deps = [
        "ext:openzl_ext",  # @manual
    ],
)
