// Copyright (c) Meta Platforms, Inc. and affiliates.

#ifndef OPENZL_CODECS_SDDL2_H
#define OPENZL_CODECS_SDDL2_H

#include <stddef.h>
#include "openzl/zl_opaque_types.h"
#include "openzl/zl_segmenter.h"

#if defined(__cplusplus)
extern "C" {
#endif

/**
 * Graph ID for the SDDL2 (Simple Data Description Language v2) component.
 *
 * This is an enhanced bytecode execution engine for parsing and decomposing
 * structured data. It provides significant performance improvements over SDDL
 * v1 while maintaining compatibility with the OpenZL compression framework.
 *
 * The public SDDL2 graph is an auto-segmenting graph.
 *
 * It requires:
 * 1. Bytecode parameter (SDDL2_BYTECODE_PARAM)
 *
 * It may also be given:
 * 1. A successor graph to process the parsed segments. If omitted, the graph
 *    defaults to ZL_GRAPH_COMPRESS_GENERIC.
 * 2. A chunk-size hint through SDDL2_CHUNK_BYTE_SIZE_PARAM or
 *    ZL_Compressor_registerSDDL2Graph_advanced().
 *
 * Use the C++ wrapper openzl::graphs::SDDL2 for convenient graph construction.
 */
#define ZL_GRAPH_SDDL2                                         \
    (ZL_GraphID)                                               \
    {                                                          \
        ZL_StandardGraphID_simple_data_description_language_v2 \
    }

/**
 * Parameter ID at which the SDDL2 graph expects to receive the bytecode it
 * will execute.
 *
 * The bytecode should be generated by the SDDL compiler or assembler and
 * passed as a local copy parameter.
 */
#define SDDL2_BYTECODE_PARAM 7685

/**
 * Default target chunk size applied by the public SDDL2 segmenter when no
 * chunk-size hint is provided.
 */
#define SDDL2_DEFAULT_CHUNK_BYTE_SIZE ZL_DEFAULT_SEGMENTER_CHUNK_BYTE_SIZE

/**
 * Optional parameter ID for setting the maximum target chunk size of the
 * public SDDL2 segmenter.
 *
 * When this parameter is omitted, or set to 0, the segmenter defaults to
 * SDDL2_DEFAULT_CHUNK_BYTE_SIZE.
 */
#define SDDL2_CHUNK_BYTE_SIZE_PARAM 7686

/**
 * Registers a Simple Data Description Language v2 graph with the provided
 * (pre-compiled) @p bytecode.
 *
 * This configures the standard auto-segmenting SDDL2 graph with bytecode, the
 * default successor graph ZL_GRAPH_COMPRESS_GENERIC, and the default chunking
 * behavior (equivalent to omitting SDDL2_CHUNK_BYTE_SIZE_PARAM, which resolves
 * to SDDL2_DEFAULT_CHUNK_BYTE_SIZE at runtime).
 *
 * @param compressor The compressor instance to register the graph with
 * @param bytecode Pointer to the compiled SDDL2 bytecode
 * @param bytecode_size Size of the bytecode in bytes
 * @return The registered graph ID
 *
 * @note The bytecode should be generated by the SDDL compiler or assembler.
 *       The bytecode format is documented in the SDDL2 specification.
 */
ZL_GraphID ZL_Compressor_registerSDDL2Graph(
        ZL_Compressor* compressor,
        const void* bytecode,
        size_t bytecode_size);

/**
 * Registers a Simple Data Description Language v2 graph with the provided
 * (pre-compiled) @p bytecode, explicit @p destination graph, and optional
 * chunking hint.
 *
 * Use this variant when the default successor graph or single-chunk behavior
 * is not appropriate.
 *
 * @param compressor The compressor instance to register the graph with
 * @param bytecode Pointer to the compiled SDDL2 bytecode
 * @param bytecode_size Size of the bytecode in bytes
 * @param destination The graph to process the parsed segments
 * @param chunk_byte_size Optional max chunk size in bytes. Pass 0 to use the
 * default SDDL2_DEFAULT_CHUNK_BYTE_SIZE chunking.
 * @return The registered graph ID
 *
 * @note The bytecode should be generated by the SDDL compiler or assembler.
 *       The bytecode format is documented in the SDDL2 specification.
 */
ZL_GraphID ZL_Compressor_registerSDDL2Graph_advanced(
        ZL_Compressor* compressor,
        const void* bytecode,
        size_t bytecode_size,
        ZL_GraphID destination,
        size_t chunk_byte_size);

#if defined(__cplusplus)
}
#endif

#endif // OPENZL_CODECS_SDDL2_H
