# Copyright (c) Meta Platforms, Inc. and affiliates.

# @noautodeps

load("@fbcode_macros//build_defs:cpp_binary.bzl", "cpp_binary")

oncall("data_compression")

cpp_binary(
    name = "thrift_config_builder",
    srcs = ["thrift_config_builder.cpp"],
    deps = [
        "../../custom_transforms/thrift:thrift_lib",
        "//folly:base64",
    ],
)
