// Copyright (c) Meta Platforms, Inc. and affiliates.

#ifndef OPENZL_DECOMPRESS_DECODER_FUSION_H
#define OPENZL_DECOMPRESS_DECODER_FUSION_H

#include <stdint.h>

#include "openzl/common/allocation.h"
#include "openzl/common/buffer_internal.h"
#include "openzl/common/map.h"
#include "openzl/decompress/dctx2.h"
#include "openzl/decompress/decode_frameheader.h"
#include "openzl/decompress/dtransforms.h"
#include "openzl/zl_errors.h"
#include "openzl/zl_opaque_types.h"

typedef struct {
    /**
     * Codec ID of the child. This codec feeds its regenerated streams into the
     * parent.
     */
    ZL_IDType codec;
    /// Number of streams regenerated by the child codec.
    uint32_t numRegens;
    /// The parent index that each regenerated stream maps to.
    const uint32_t* parentIndices;
} ZL_DecoderFusionChild;

/**
 * This struct describes the codecs that participate in a fused decoder.
 *
 * The @p parentCodec is the final codec in the graph. Currently only a single
 * parent codec is supported.
 *
 * The @p children are the child codecs that feed ALL of their regenerated
 * streams into the parent codec. Each child codec can regenerate one or more
 * streams. Not all of the parent's inputs need to be regenerated by the
 * @p children.
 *
 * This means that the pattern can only fuse a single layer of child codecs
 * who feed all their regenerated streams into a single parent.
 *
 * @note This pattern matching scheme can be changed as need when the need
 * arises to fuse more complicated codec combinations. Fusion is a private API,
 * so we can change all callers in a refactor.
 */
typedef struct {
    /// Codec ID of the parent codec.
    ZL_IDType parentCodec;
    /// Number of fused child codecs.
    uint32_t numChildren;
    /// The fused child codecs.
    const ZL_DecoderFusionChild* children;
} ZL_DecoderFusionPattern;

/**
 * State passed to a fused decoder function.
 * Contains the decompression context and all codec information needed
 * to execute the fused decoder graph.
 *
 * Arrays indexed by codec use the convention that indices [0, numCodecs-2]
 * correspond to pattern.children[0..numChildren-1] (the child codecs), and
 * index [numCodecs-1] is the parent codec (pattern.parentCodec).
 */
typedef struct ZL_DecoderFusion_s {
    /// The decompression context.
    ZL_DCtx* dctx;
    /// Arena for temporary allocations during fused decoding.
    Arena* workspaceArena;
    /// Frame header node info for each codec in the fusion.
    const DFH_NodeInfo* const* nodeInfos;
    /// The decoder transform for each codec in the fusion.
    const DTransform* const* codecs;
    /// The private codec header for each codec in the fusion.
    const ZL_RBuffer* codecHeaders;
    /// The input streams for each codec in the fusion.
    const ZL_Data*** codecInputs;
    /// The number of codecs in the fusion (children + parent).
    size_t numCodecs;
    /// The stream IDs for the parent codec's regenerated streams.
    const ZL_IDType* regenStreamIDs;
    /// The number of regenerated streams for the parent codec.
    size_t numRegenStreams;
} ZL_DecoderFusion;

/// Allocate scratch space from the fusion's workspace arena.
/// @return Pointer to the allocated memory, or NULL on allocation failure.
void* ZL_DecoderFusion_getScratchSpace(ZL_DecoderFusion* state, size_t size);

/**
 * Create a typed output stream for the parent codec's regenerated stream at
 * @p index.
 * @return The output stream, or NULL on failure.
 */
ZL_Output* ZL_DecoderFusion_createTypedStream(
        ZL_DecoderFusion* state,
        int index,
        size_t eltsCapacity,
        size_t eltWidth);

/**
 * Create a string output stream for the parent codec's regenerated stream at
 * @p index.
 * @return The output stream, or NULL on failure.
 */
ZL_Output* ZL_DecoderFusion_createStringStream(
        ZL_DecoderFusion* state,
        int index,
        size_t nbStringsMax,
        size_t sumStringLensMax);

/**
 * Get the private codec header for the codec at @p idx in the fusion.
 * @p idx in [0, numCodecs-2] corresponds to pattern.children[idx], and
 * @p idx == numCodecs-1 is the parent codec (pattern.parentCodec).
 */
ZL_RESULT_OF(ZL_RBuffer)
ZL_DecoderFusion_getCodecHeader(const ZL_DecoderFusion* state, size_t idx);

/// A read-only array of input streams.
typedef struct {
    const ZL_Input* const* inputs;
    size_t numInputs;
} ZL_InputArray;

ZL_RESULT_DECLARE_TYPE(ZL_InputArray);

/// The input streams for a codec, split into singleton and variable inputs.
typedef struct {
    /// The singleton (fixed) input streams.
    ZL_InputArray singleton;
    /// The variable input streams.
    ZL_InputArray variable;
} ZL_CodecInputs;

ZL_RESULT_DECLARE_TYPE(ZL_CodecInputs);

/**
 * Get the input streams for the codec at @p idx in the fusion.
 * @p idx in [0, numCodecs-2] corresponds to pattern.children[idx], and
 * @p idx == numCodecs-1 is the parent codec (pattern.parentCodec).
 * @note Inputs will be NULL after ZL_DecoderFusion_runCodec() is called for
 * this codec, because the decoder frees its input streams.
 * @note When called on the parent codec, inputs produced by fused codecs will
 * be NULL.
 */
ZL_RESULT_OF(ZL_CodecInputs)
ZL_DecoderFusion_getCodecInputs(const ZL_DecoderFusion* state, size_t idx);

/**
 * Run the default (non-fused) decoder for the codec at @p idx in the fusion,
 * and return its regenerated output streams.
 * @p idx in [0, numCodecs-2] corresponds to pattern.children[idx], and
 * @p idx == numCodecs-1 is the parent codec (pattern.parentCodec).
 */
ZL_RESULT_OF(ZL_InputArray)
ZL_DecoderFusion_runCodec(ZL_DecoderFusion* state, size_t idx);

/// The fused decoder function. Called instead of running each codec
/// individually when the fusion pattern matches.
typedef ZL_Report (*ZL_DecoderFusionFn)(ZL_DecoderFusion* fusion);

/// Describes a decoder fusion: a pattern to match and a function to execute.
typedef struct ZL_DecoderFusionDesc_s {
    /// The codec graph pattern that this fusion matches.
    ZL_DecoderFusionPattern pattern;
    /// The fused decoder function to call when the pattern matches.
    ZL_DecoderFusionFn fusionFn;
} ZL_DecoderFusionDesc;

/// A contiguous range of indices [begin, begin + size).
typedef struct {
    uint32_t begin;
    uint32_t size;
} ZL_IndexRange;

ZL_DECLARE_MAP_TYPE(ZL_DecoderFusionMap, ZL_IDType, ZL_IndexRange);

/// Manages the set of registered decoder fusions and provides lookup by
/// parent codec ID.
typedef struct {
    /// Arena for all dynamic allocations owned by this state.
    Arena* arena;
    /// Map from parent codec ID to the range of fusions in @p codecFusions.
    ZL_DecoderFusionMap codecFusionMap;
    /// Sorted array of all registered fusions, ordered by parent codec ID.
    const ZL_DecoderFusionDesc* codecFusions;
    /// Number of registered fusions.
    size_t numCodecFusions;
    /// Owned storage for dynamically registered fusions (NULL if only
    /// using the static ZL_DecoderFusion_array).
    ZL_DecoderFusionDesc* codecFusionStorage;
} ZL_DecoderFusionState;

/// Initialize the fusion state with the built-in fusions from the registry.
ZL_Report ZL_DecoderFusionState_init(ZL_DecoderFusionState* state);

/// Remove all registered fusions from the state, including built-in fusions
/// from the registry.
void ZL_DecoderFusionState_clearFusions(ZL_DecoderFusionState* state);

/// Register a new decoder fusion. The fusion descriptor and its children are
/// deep-copied into the state's arena.
ZL_Report ZL_DecoderFusionState_registerFusion(
        ZL_DecoderFusionState* state,
        const ZL_DecoderFusionDesc* fusion);

/// Destroy the fusion state and free all associated memory.
void ZL_DecoderFusionState_destroy(ZL_DecoderFusionState* state);

/**
 * Check if @p fusion matches the codec graph rooted at @p parentNodeIndex.
 * If it matches, mark the parent and all matching child nodes as fused.
 * @return true if the fusion was applied, false otherwise.
 */
bool ZL_DecoderFusionDesc_fuseIfMatches(
        const ZL_DecoderFusionDesc* fusion,
        DFH_NodeInfo* nodeInfo,
        const ZL_DCtx_DataInfo* dataInfo,
        size_t parentNodeIndex);

/**
 * Try to fuse the codec graph rooted at @p parentNodeIndex by checking all
 * registered fusions for that codec ID.
 * @return true if a fusion was applied, false otherwise.
 */
static inline bool ZL_DecoderFusionState_maybeFuse(
        const ZL_DecoderFusionState* state,
        DFH_NodeInfo* nodeInfo,
        const ZL_DCtx_DataInfo* dataInfo,
        size_t parentNodeIndex)
{
    PublicTransformInfo codecInfo = nodeInfo[parentNodeIndex].trpid;
    if (codecInfo.trt != trt_standard) {
        return false;
    }
    const ZL_DecoderFusionMap_Entry* entry =
            ZL_DecoderFusionMap_findVal(&state->codecFusionMap, codecInfo.trid);
    if (entry == NULL) {
        return false;
    }

    for (size_t i = 0; i < entry->val.size; ++i) {
        if (ZL_DecoderFusionDesc_fuseIfMatches(
                    &state->codecFusions[entry->val.begin + i],
                    nodeInfo,
                    dataInfo,
                    parentNodeIndex)) {
            return true;
        }
    }

    return false;
}

/// Check if @p nodeInfo is the parent node of @p fusion.
static inline bool ZL_DecoderFusionDesc_isParent(
        const ZL_DecoderFusionDesc* fusion,
        const DFH_NodeInfo* nodeInfo)
{
    ZL_ASSERT(!fusion || nodeInfo->trpid.trt == trt_standard);
    return fusion && nodeInfo->trpid.trid == fusion->pattern.parentCodec;
}

/**
 * Get the node index of the codec that produces the first regenerated stream
 * for child @p childIdx in the fusion.
 * @return The producer node index, or ZL_PRODUCER_STORE if the stream is
 * stored in the frame.
 */
ZL_IDType ZL_DecoderFusionDesc_getProducerNodeIdx(
        const ZL_DecoderFusionDesc* fusion,
        size_t childIdx,
        const DFH_NodeInfo* parentNodeInfo,
        const ZL_DCtx_DataInfo* dataInfo);

#endif
