# Copyright (c) Meta Platforms, Inc. and affiliates.

load("../../../defs.bzl", "zs_cxxbinary", "zs_cxxlibrary")

oncall("data_compression")

zs_cxxlibrary(
    name = "lib",
    srcs = glob(
        [
            "*.cpp",
        ],
        exclude = ["main.cpp"],
    ),
    headers = glob([
        "*.h",
    ]),
    exported_deps = [
        "../../../cpp:openzl_cpp",
    ],
)

zs_cxxbinary(
    name = "compiler",
    srcs = ["main.cpp"],
    deps = [
        ":lib",
    ],
)
