# Copyright (c) Meta Platforms, Inc. and affiliates.

load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load("../../../defs.bzl", "relative_headers")

oncall("data_compression")

cpp_unittest(
    # @autodeps-skip
    name = "test_training",
    srcs = [
        "test_ace.cpp",
        "test_ace_combination.cpp",
        "test_clustering.cpp",
        "test_clustering_benchmarks.cpp",
        "test_clustering_config_builder.cpp",
        "test_genetic_algorithm.cpp",
        "test_sample_collection.cpp",
        "test_sample_limiter.cpp",
        "test_thread_pool.cpp",
    ],
    headers = relative_headers([
        "benchmark_files/ppmf_unit_segment.h",
    ]),
    header_namespace = "",
    deps = [
        "..:train",
        "../../..:zstronglib",
        "../../../custom_parsers:custom_parsers",
        "../../../custom_parsers/csv:csv_parser",
        "../../../tests/datagen:datagen",
        "../ace:automated_compressor_explorer",
        "../clustering:clustering_graph_trainer",
        "../clustering:train_api",
        "../clustering:training_clustering",
        "../utils:genetic_algorithm",
        "../utils:training_utils",
    ],
)
