# Copyright (c) Meta Platforms, Inc. and affiliates.

load("../../../../defs.bzl", "zs_unittest")

oncall("data_compression")

zs_unittest(
    name = "test_compiler",
    srcs = glob([
        "*.cpp",
    ]),
    headers = glob([
        "*.hpp",
    ]),
    deps = [
        "..:lib",
    ],
)
