// Copyright (c) Meta Platforms, Inc. and affiliates.

#ifndef OPENZL_DICT_BUNDLE_H
#define OPENZL_DICT_BUNDLE_H

#include "openzl/common/allocation.h"
#include "openzl/zl_dict.h"
#include "openzl/zl_errors.h"

#if defined(__cplusplus)
extern "C" {
#endif

// ============================================================================
// ZL_BundleInfo - Wire format parsing/packing
// ============================================================================

/**
 * Packed wire format for a serialized BundleInfo.
 *
 *   offset  size   field
 *   ------  -----  ------------------------------------------------
 *     0       4    magic       – 32-bit LE, must be 0x4942CCDA
 *     4      32    bundleID    – 256-bit LE ZL_DictBundleID
 *    36       1    isFatBundle - 0 for standalone bundle info, 1 if the parser
 *                                should additionally expect to find the
 *                                constituent dicts attached to the info
 *    37       4    numDicts    – 32-bit LE number of dictionaries
 *    41    N*32    dictIDs     – array of N ZL_DictID (each 256-bit LE)
 *
 *   Total packed size = 41 + numDicts * 32
 *
 * A "fat bundle" consists of a packed BundleInfo followed by a
 * concatenation of all constituent packed dicts.
 */
ZL_Report
BundleInfo_pack(void* dst, size_t dstCapacity, const ZL_BundleInfo* info);

// ============================================================================
// ZL_DictBundle - Packing and parsing
// ============================================================================

/**
 * Takes an array of pre-packed packed dictionary content (generated by
 * training) and packs it into a single "fat" bundle blob containing the
 * ZL_BundleInfo, followed by a concatenation of all the packed dicts.
 *
 * NOTE: the corresponding unpacking function is
 * ZL_FatBundleDictLoader_loadFatBundle().
 *
 * @pre @p dicts are well-formed packed dicts generated using ZL_Dict_pack().
 */
ZL_Report ZL_DictBundle_packFatBundle(
        void* dst,
        size_t dstCapacity,
        const void** dicts,
        size_t* dictSizes,
        size_t numDicts);

#if defined(__cplusplus)
} // extern "C"
#endif

#endif // OPENZL_DICT_BUNDLE_H
