# Copyright (c) Meta Platforms, Inc. and affiliates.

# @noautodeps
load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("data_compression")

cpp_unittest(
    name = "test_io",
    srcs = glob([
        "*.cpp",
    ]),
    headers = glob([
        "*.hpp",
    ]),
    deps = [
        "../..:io",
    ],
)
