// Copyright (c) Meta Platforms, Inc. and affiliates.
/**
 * Round-trip tests for fixed SDDL2 bytecode fixtures.
 *
 * These tests exercise the supported public `!zl.sddl2` graph using
 * pre-assembled bytecode fixtures. They preserve bytecode-level coverage for
 * typed segment replay, endianness handling, arrays, and structure splitting
 * while staying on supported graph entrypoints.
 *
 * The tests use pre-assembled SDDL2 bytecode files generated by
 * tools/sddl2/assembler/sddl2_assembler.py from .asm source files.
 * Assembly source is included in comments for documentation.
 *
 * FUTURE IMPROVEMENT:
 * Currently, bytecode must be generated externally using the Python assembler,
 * which creates a disconnect between the test and its assembly source.
 * A potential improvement would be to implement a C version of the SDDL2
 * assembler that could be used directly in tests, allowing assembly source
 * to be embedded as string literals and assembled at runtime:
 *
 *     const char* assembly = R"(
 *         push.u64 10
 *         push.type U8
 *         segment.create_tagged
 *         halt
 *     )";
 *     auto bytecode = SDDL2_assemble(assembly);
 *
 * This would improve maintainability and make the relationship between
 * test intent and bytecode clearer, eliminating the manual pre-compilation
 * step when opcodes change.
 */

#include <array>
#include <cstring>
#include <string>
#include <vector>

#include <gtest/gtest.h>

#include "tests/compress/graphs/sddl2/utils.h"

#include "openzl/cpp/CompressIntrospectionHooks.hpp"
#include "openzl/cpp/DecompressIntrospectionHooks.hpp"
#include "openzl/zl_compress.h"
#include "openzl/zl_compressor.h"
#include "openzl/zl_config.h"
#include "openzl/zl_decompress.h"
#include "openzl/zl_graph_api.h"
#include "openzl/zl_localParams.h"
#include "openzl/zl_version.h"

extern "C" {
#include "openzl/compress/graphs/sddl2/sddl2.h"
#include "openzl/compress/graphs/sddl2/sddl2_vm.h"
}

#include "sddl2_parse_test_data.h"

namespace {

/**
 * Compress using the public auto-segmenting SDDL2 graph.
 */
static size_t compress_sddl2_graph(
        void* dst,
        size_t dstCapacity,
        const void* src,
        size_t srcSize,
        const void* bytecode,
        size_t bytecode_size,
        int format_version                        = ZL_MAX_FORMAT_VERSION,
        size_t chunk_byte_size                    = 0,
        openzl::CompressIntrospectionHooks* hooks = nullptr)
{
    assert(dstCapacity >= ZL_compressBound(srcSize));

    ZL_CCtx* const cctx = ZL_CCtx_create();
    assert(cctx);

    // Set format version (required parameter)
    ZL_Report const fvr =
            ZL_CCtx_setParameter(cctx, ZL_CParam_formatVersion, format_version);
    EXPECT_EQ(ZL_isError(fvr), 0) << "Failed to set format version";

    ZL_Compressor* const cgraph = ZL_Compressor_create();
    assert(cgraph);

    ZL_GraphID sddl2_gid = chunk_byte_size == 0
            ? ZL_Compressor_registerSDDL2Graph(cgraph, bytecode, bytecode_size)
            : ZL_Compressor_registerSDDL2Graph_advanced(
                      cgraph,
                      bytecode,
                      bytecode_size,
                      ZL_GRAPH_COMPRESS_GENERIC,
                      chunk_byte_size);
    EXPECT_NE(sddl2_gid.gid, ZL_GRAPH_ILLEGAL.gid)
            << "Failed to register public SDDL2 graph";

    ZL_Report const selr =
            ZL_Compressor_selectStartingGraphID(cgraph, sddl2_gid);
    EXPECT_EQ(ZL_isError(selr), 0) << "Failed to select SDDL2 graph\n";

    if (hooks != nullptr) {
        ZL_Report const attachr =
                ZL_CCtx_attachIntrospectionHooks(cctx, hooks->getRawHooks());
        EXPECT_EQ(ZL_isError(attachr), 0)
                << "Failed to attach compression introspection hooks";
        if (ZL_isError(attachr)) {
            ZL_Compressor_free(cgraph);
            ZL_CCtx_free(cctx);
            return 0;
        }
    }

    ZL_Report const rcgr = ZL_CCtx_refCompressor(cctx, cgraph);
    EXPECT_EQ(ZL_isError(rcgr), 0) << "CGraph reference failed\n";

    ZL_Report const r = ZL_CCtx_compress(cctx, dst, dstCapacity, src, srcSize);
    if (ZL_isError(r)) {
        const char* errCtx = ZL_CCtx_getErrorContextString(cctx, r);
        EXPECT_EQ(ZL_isError(r), 0) << "compression failed\nError context: "
                                    << (errCtx ? errCtx : "none");
        ZL_Compressor_free(cgraph);
        ZL_CCtx_free(cctx);
        return 0;
    }

    ZL_Compressor_free(cgraph);
    ZL_CCtx_free(cctx);

    return ZL_validResult(r);
}

struct ReplayChunkCompressResult {
    ZL_Report report;
    size_t compressedSize;
    std::string errorContext;
};

static ReplayChunkCompressResult compress_sddl2_replay_chunk_with_result(
        void* dst,
        size_t dstCapacity,
        const void* src,
        size_t srcSize,
        const ZL_LocalParams* local_params)
{
    assert(dstCapacity >= ZL_compressBound(srcSize));

    ReplayChunkCompressResult result{};

    ZL_CCtx* const cctx = ZL_CCtx_create();
    assert(cctx);

    ZL_Report const fvr = ZL_CCtx_setParameter(
            cctx, ZL_CParam_formatVersion, ZL_MAX_FORMAT_VERSION);
    EXPECT_EQ(ZL_isError(fvr), 0) << "Failed to set format version";
    ZL_Report const msr =
            ZL_CCtx_setParameter(cctx, ZL_CParam_minStreamSize, -1);
    EXPECT_EQ(ZL_isError(msr), 0) << "Failed to disable auto-store threshold";

    ZL_Compressor* const cgraph = ZL_Compressor_create();
    assert(cgraph);

    ZL_LocalParams const params =
            local_params != nullptr ? *local_params : ZL_LocalParams{};
    ZL_Type inputType                            = ZL_Type_serial;
    ZL_FunctionGraphDesc const sddl2_replay_desc = {
        .name                = "sddl2_replay_chunk",
        .graph_f             = SDDL2_replayChunk,
        .inputTypeMasks      = &inputType,
        .nbInputs            = 1,
        .lastInputIsVariable = false,
        .localParams         = params,
    };

    ZL_GraphID replay_gid =
            ZL_Compressor_registerFunctionGraph(cgraph, &sddl2_replay_desc);
    EXPECT_NE(replay_gid.gid, ZL_GRAPH_ILLEGAL.gid)
            << "Failed to register SDDL2_replayChunk";

    ZL_Report const selr =
            ZL_Compressor_selectStartingGraphID(cgraph, replay_gid);
    EXPECT_EQ(ZL_isError(selr), 0) << "Failed to select SDDL2_replayChunk\n";

    ZL_Report const rcgr = ZL_CCtx_refCompressor(cctx, cgraph);
    EXPECT_EQ(ZL_isError(rcgr), 0) << "CGraph reference failed\n";

    result.report = ZL_CCtx_compress(cctx, dst, dstCapacity, src, srcSize);
    if (ZL_isError(result.report)) {
        const char* errCtx = ZL_CCtx_getErrorContextString(cctx, result.report);
        result.errorContext = errCtx != nullptr ? errCtx : "";
    } else {
        result.compressedSize = ZL_validResult(result.report);
    }

    ZL_Compressor_free(cgraph);
    ZL_CCtx_free(cctx);
    return result;
}

static size_t compress_sddl2_replay_chunk(
        void* dst,
        size_t dstCapacity,
        const void* src,
        size_t srcSize,
        const SDDL2_ReplaySegment* segments,
        size_t num_segments,
        int start_stream_id)
{
    ZL_IntParam startStreamParam = {
        SDDL2_REPLAY_START_STREAM_ID_PARAM,
        start_stream_id,
    };
    ZL_RefParam replaySegmentsParam = {
        SDDL2_REPLAY_SEGMENTS_PARAM,
        segments,
        num_segments * sizeof(*segments),
    };

    ZL_LocalIntParams intParams = {
        .intParams   = &startStreamParam,
        .nbIntParams = 1,
    };
    ZL_LocalRefParams refParams = {
        .refParams   = &replaySegmentsParam,
        .nbRefParams = 1,
    };
    ZL_LocalParams params = {
        .intParams = intParams,
        .refParams = refParams,
    };

    ReplayChunkCompressResult const result =
            compress_sddl2_replay_chunk_with_result(
                    dst, dstCapacity, src, srcSize, &params);
    if (ZL_isError(result.report)) {
        EXPECT_EQ(ZL_isError(result.report), 0)
                << "compression failed\nError context: "
                << (result.errorContext.empty() ? "none"
                                                : result.errorContext.c_str());
        return 0;
    }
    return result.compressedSize;
}

/**
 * Decompress
 */
static size_t decompress(
        void* dst,
        size_t dstCapacity,
        const void* src,
        size_t srcSize,
        openzl::DecompressIntrospectionHooks* hooks = nullptr)
{
    ZL_Report const dr = ZL_getDecompressedSize(src, srcSize);
    assert(!ZL_isError(dr));
    size_t const dstSize = ZL_validResult(dr);
    assert(dstCapacity >= dstSize);
    (void)dstSize;

    ZL_DCtx* const dctx = ZL_DCtx_create();
    assert(dctx);

    if (hooks != nullptr) {
        ZL_Report const attachr = ZL_DCtx_attachDecompressIntrospectionHooks(
                dctx, hooks->getRawHooks());
        EXPECT_EQ(ZL_isError(attachr), 0)
                << "Failed to attach decompression introspection hooks";
        if (ZL_isError(attachr)) {
            ZL_DCtx_free(dctx);
            return 0;
        }
    }

    ZL_Report const r =
            ZL_DCtx_decompress(dctx, dst, dstCapacity, src, srcSize);
    EXPECT_EQ(ZL_isError(r), 0) << "decompression failed \n";

    ZL_DCtx_free(dctx);

    return ZL_validResult(r);
}

/**
 * Round-trip helper for the public SDDL2 graph.
 */
static void roundtrip_test(
        const void* input,
        size_t inputSize,
        const void* bytecode,
        size_t bytecode_size,
        const char* testName)
{
    size_t const compressedBound = ZL_compressBound(inputSize);
    void* const compressed       = malloc(compressedBound);
    assert(compressed);

    size_t const compressedSize = compress_sddl2_graph(
            compressed,
            compressedBound,
            input,
            inputSize,
            bytecode,
            bytecode_size);
    EXPECT_GT(compressedSize, 0u) << testName << ": compression returned 0";

    void* const decompressed = malloc(inputSize);
    assert(decompressed);

    size_t const decompressedSize =
            decompress(decompressed, inputSize, compressed, compressedSize);
    EXPECT_EQ(decompressedSize, inputSize)
            << testName << ": decompressed size mismatch";

    EXPECT_EQ(std::memcmp(decompressed, input, inputSize), 0)
            << testName << ": decompressed data doesn't match input";

    free(decompressed);
    free(compressed);
}

#if ZL_ALLOW_INTROSPECTION
static void roundtrip_test_with_chunk_count(
        const void* input,
        size_t inputSize,
        const void* bytecode,
        size_t bytecode_size,
        int format_version,
        size_t chunk_byte_size,
        size_t expected_chunks,
        const char* testName)
{
    size_t const compressedBound = ZL_compressBound(inputSize);
    void* const compressed       = malloc(compressedBound);
    assert(compressed);

    openzl::sddl2::testing::CompressChunkCounterHook compress_hook;
    size_t const compressedSize = compress_sddl2_graph(
            compressed,
            compressedBound,
            input,
            inputSize,
            bytecode,
            bytecode_size,
            format_version,
            chunk_byte_size,
            &compress_hook);
    EXPECT_GT(compressedSize, 0u) << testName << ": compression returned 0";
    EXPECT_EQ(compress_hook.chunkCount, expected_chunks)
            << testName << ": unexpected compression chunk count";

    void* const decompressed = malloc(inputSize);
    assert(decompressed);

    openzl::sddl2::testing::DecompressChunkCounterHook decompress_hook;
    size_t const decompressedSize = decompress(
            decompressed,
            inputSize,
            compressed,
            compressedSize,
            &decompress_hook);
    EXPECT_EQ(decompressedSize, inputSize)
            << testName << ": decompressed size mismatch";
    EXPECT_EQ(decompress_hook.chunkCount, expected_chunks)
            << testName << ": unexpected decompression chunk count";

    EXPECT_EQ(std::memcmp(decompressed, input, inputSize), 0)
            << testName << ": decompressed data doesn't match input";

    free(decompressed);
    free(compressed);
}
#endif

static SDDL2_Type primitive_type(SDDL2_Type_kind kind, uint32_t width)
{
    SDDL2_Type type{};
    type.kind         = kind;
    type.width        = width;
    type.complex_data = nullptr;
    return type;
}

static SDDL2_ReplaySegment primitive_replay_segment(
        size_t size_bytes,
        SDDL2_Type_kind kind,
        uint32_t width)
{
    SDDL2_ReplaySegment segment{};
    segment.size_bytes = size_bytes;
    segment.type       = primitive_type(kind, width);
    return segment;
}

static SDDL2_Struct_data* create_structure_data(
        const SDDL2_Type* members,
        size_t member_count)
{
    size_t const alloc_size =
            sizeof(SDDL2_Struct_data) + member_count * sizeof(*members);
    auto* const struct_data = (SDDL2_Struct_data*)malloc(alloc_size);
    assert(struct_data != nullptr);

    struct_data->member_count     = member_count;
    struct_data->total_size_bytes = 0;
    for (size_t i = 0; i < member_count; ++i) {
        struct_data->members[i] = members[i];
        struct_data->total_size_bytes +=
                openzl::sddl2::testing::getTypeSize(members[i]);
    }

    return struct_data;
}

static SDDL2_ReplaySegment structure_replay_segment(
        size_t size_bytes,
        SDDL2_Struct_data* struct_data)
{
    SDDL2_ReplaySegment segment{};
    segment.size_bytes       = size_bytes;
    segment.type.kind        = SDDL2_TYPE_STRUCTURE;
    segment.type.width       = 1;
    segment.type.struct_data = struct_data;
    return segment;
}

static void replay_roundtrip_test(
        const void* input,
        size_t inputSize,
        const SDDL2_ReplaySegment* segments,
        size_t num_segments,
        int start_stream_id,
        const char* testName)
{
    size_t const compressedBound = ZL_compressBound(inputSize);
    void* const compressed       = malloc(compressedBound);
    assert(compressed);

    size_t const compressedSize = compress_sddl2_replay_chunk(
            compressed,
            compressedBound,
            input,
            inputSize,
            segments,
            num_segments,
            start_stream_id);
    EXPECT_GT(compressedSize, 0u) << testName << ": compression returned 0";

    void* const decompressed = malloc(inputSize);
    assert(decompressed);

    size_t const decompressedSize =
            decompress(decompressed, inputSize, compressed, compressedSize);
    EXPECT_EQ(decompressedSize, inputSize)
            << testName << ": decompressed size mismatch";

    EXPECT_EQ(std::memcmp(decompressed, input, inputSize), 0)
            << testName << ": decompressed data doesn't match input";

    free(decompressed);
    free(compressed);
}

/**
 * Test: Single U8 typed segment
 *
 * Assembly source (test_data/single_u8_segment.asm):
 *   push.tag 0
 *   push.type.u8
 *   push.i32 4
 *   segment.create_tagged
 *   halt
 */
TEST(SDDL2BytecodeTest, SingleU8Segment)
{
    std::array<uint8_t, 4> input = { 0xAA, 0xBB, 0xCC, 0xDD };

    roundtrip_test(
            input.data(),
            input.size(),
            sddl2_parse_test_data::SINGLE_U8_SEGMENT.data(),
            sddl2_parse_test_data::SINGLE_U8_SEGMENT.size(),
            "SingleU8Segment");
}

/**
 * Test: Single I32LE typed segment
 *
 * Assembly source (test_data/single_i32le_segment.asm):
 *   push.tag 100
 *   push.type.i32le
 *   push.i32 1
 *   segment.create_tagged
 *   halt
 */
TEST(SDDL2BytecodeTest, SingleI32LESegment)
{
    std::array<uint8_t, 4> input = { 0x2A, 0x00, 0x00, 0x00 }; // 42 in LE

    roundtrip_test(
            input.data(),
            input.size(),
            sddl2_parse_test_data::SINGLE_I32LE_SEGMENT.data(),
            sddl2_parse_test_data::SINGLE_I32LE_SEGMENT.size(),
            "SingleI32LESegment");
}

/**
 * Test: BYTES segment (no conversion)
 *
 * Assembly source (test_data/bytes_segment.asm):
 *   push.i32 5
 *   segment.create_unspecified
 *   halt
 */
TEST(SDDL2BytecodeTest, BytesSegmentNoConversion)
{
    std::array<uint8_t, 5> input = { 'H', 'e', 'l', 'l', 'o' };

    roundtrip_test(
            input.data(),
            input.size(),
            sddl2_parse_test_data::BYTES_SEGMENT.data(),
            sddl2_parse_test_data::BYTES_SEGMENT.size(),
            "BytesSegmentNoConversion");
}

/**
 * Test: Mixed type segments (U8, I32LE, BYTES)
 *
 * Assembly source (test_data/mixed_segments.asm):
 *   # Segment 1: U8[4]
 *   push.tag 1
 *   push.type.u8
 *   push.i32 4
 *   segment.create_tagged
 *
 *   # Segment 2: I32LE[1]
 *   push.tag 2
 *   push.type.i32le
 *   push.i32 1
 *   segment.create_tagged
 *
 *   # Segment 3: BYTES[4]
 *   push.i32 4
 *   segment.create_unspecified
 *   halt
 */
TEST(SDDL2BytecodeTest, MixedTypeSegments)
{
    std::array<uint8_t, 12> input = {
        0xAA, 0xBB, 0xCC, 0xDD, // Segment 1
        0x2A, 0x00, 0x00, 0x00, // Segment 2
        0x01, 0x02, 0x03, 0x04  // Segment 3
    };

    roundtrip_test(
            input.data(),
            input.size(),
            sddl2_parse_test_data::MIXED_SEGMENTS.data(),
            sddl2_parse_test_data::MIXED_SEGMENTS.size(),
            "MixedTypeSegments");
}

/**
 * Test: U16BE big-endian segment
 *
 * Assembly source (test_data/u16be_segment.asm):
 *   push.tag 50
 *   push.type.u16be
 *   push.i32 4
 *   segment.create_tagged
 *   halt
 */
TEST(SDDL2BytecodeTest, U16BESegmentBigEndian)
{
    std::array<uint8_t, 8> input = { 0x12, 0x34, 0x56, 0x78,
                                     0xAB, 0xCD, 0xEF, 0x01 };

    roundtrip_test(
            input.data(),
            input.size(),
            sddl2_parse_test_data::U16BE_SEGMENT.data(),
            sddl2_parse_test_data::U16BE_SEGMENT.size(),
            "U16BESegmentBigEndian");
}

/**
 * Test: Array type segment (U32LE[10])
 *
 * Tests the type.fixed_array opcode in end-to-end compression/decompression.
 * This validates that array types correctly integrate with the public SDDL2
 * graph and that segment size calculation accounts for the array width field.
 *
 * Creates a segment containing 25 arrays, where each array is U32LE[10].
 * Total size: 25 × 10 × 4 bytes = 1000 bytes
 *
 * Assembly source (test_data/array_type_u32le_10.asm):
 *   push.tag 100
 *   push.type.u32le       ; Base type: Type{U32LE, 1}
 *   push.i32 10           ; Push array count onto stack
 *   type.fixed_array      ; Stack-based: pops count and type, creates
 * Type{U32LE, 10} push.i32 25           ; Element count: 25 arrays
 *   segment.create_tagged ; Creates 1000-byte segment (25 × 10 × 4 bytes)
 *   halt
 *
 * This creates a segment with type U32LE[10]:
 *   - kind: SDDL2_TYPE_U32LE
 *   - width: 10 (array of 10 U32LE values = 40 bytes per array)
 *   - Total size: 25 arrays × 40 bytes/array = 1000 bytes
 */
TEST(SDDL2BytecodeTest, ArrayTypeU32LE10)
{
    // Generate 25 arrays of 10 U32LE values each
    // Each array contains values [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] in
    // little-endian
    const size_t ARRAY_SIZE = 10;
    const size_t NUM_ARRAYS = 25;

    uint32_t input[NUM_ARRAYS][ARRAY_SIZE];

    // Fill with repeating pattern: each array contains [0..9]
    for (size_t array_idx = 0; array_idx < NUM_ARRAYS; array_idx++) {
        for (size_t i = 0; i < ARRAY_SIZE; i++) {
            uint32_t value      = static_cast<uint32_t>(i);
            input[array_idx][i] = value;
        }
    }

    roundtrip_test(
            input,
            sizeof(input),
            sddl2_parse_test_data::ARRAY_TYPE_U32LE_10.data(),
            sddl2_parse_test_data::ARRAY_TYPE_U32LE_10.size(),
            "ArrayTypeU32LE10");
}

#if ZL_ALLOW_INTROSPECTION
TEST(SDDL2BytecodeTest, ChunkHintIgnoredBeforeChunkFormatVersion)
{
    constexpr size_t kArraySize             = 10;
    constexpr size_t kNumArrays             = 25;
    constexpr size_t kChunkByteSize         = 2 * kArraySize * sizeof(uint32_t);
    constexpr size_t kExpectedChunkedChunks = 13;
    constexpr size_t kExpectedLegacyChunks  = 1;

    std::array<std::array<uint32_t, kArraySize>, kNumArrays> input{};
    for (size_t array_idx = 0; array_idx < kNumArrays; ++array_idx) {
        for (size_t i = 0; i < kArraySize; ++i) {
            input[array_idx][i] = static_cast<uint32_t>(i);
        }
    }

    roundtrip_test_with_chunk_count(
            input.data(),
            sizeof(input),
            sddl2_parse_test_data::ARRAY_TYPE_U32LE_10.data(),
            sddl2_parse_test_data::ARRAY_TYPE_U32LE_10.size(),
            ZL_MAX_FORMAT_VERSION,
            kChunkByteSize,
            kExpectedChunkedChunks,
            "ChunkHintIgnoredBeforeChunkFormatVersionChunked");
    roundtrip_test_with_chunk_count(
            input.data(),
            sizeof(input),
            sddl2_parse_test_data::ARRAY_TYPE_U32LE_10.data(),
            sddl2_parse_test_data::ARRAY_TYPE_U32LE_10.size(),
            ZL_CHUNK_VERSION_MIN - 1,
            kChunkByteSize,
            kExpectedLegacyChunks,
            "ChunkHintIgnoredBeforeChunkFormatVersionLegacy");
}
#endif

/**
 * Test: Structure array segment
 *
 * Tests the type.structure opcode in end-to-end compression/decompression.
 * This validates that structure types correctly integrate with the public
 * SDDL2 graph and that structure splitting, field type conversion, and
 * independent compression work correctly in a full round-trip scenario.
 *
 * Creates a segment containing 10 structures, where each structure is:
 *   {U8, I16LE, I32LE}
 * Total size: 10 × (1 + 2 + 4) bytes = 70 bytes
 *
 * Assembly source (test_data/struct_array_segment.asm):
 *   push.tag 200
 *   push.type.u8          ; Field 0: U8
 *   push.type.i16le       ; Field 1: I16LE
 *   push.type.i32le       ; Field 2: I32LE
 *   push.i32 3            ; 3 members
 *   type.structure        ; Creates Type{STRUCTURE{U8, I16LE, I32LE}, width=7}
 *   push.i32 10           ; Element count: 10 structures
 *   segment.create_tagged ; Creates 70-byte segment
 *   halt
 *
 * This tests the full structure split pipeline:
 *   1. The public SDDL2 graph recognizes the STRUCTURE type segment
 *   2. sddl2_apply_structure_split() decomposes into 3 field arrays:
 *      - Field 0: [10 × U8]   → Convert to U8   → COMPRESS_GENERIC
 *      - Field 1: [10 × I16LE] → Convert to I16LE → COMPRESS_GENERIC
 *      - Field 2: [10 × I32LE] → Convert to I32LE → COMPRESS_GENERIC
 *   3. Each field is independently compressed
 *   4. Decompression reconstructs the original structure layout
 */
TEST(SDDL2BytecodeTest, StructureArraySegment)
{
    // Generate 10 structures of {U8, I16LE, I32LE}
    const size_t NUM_STRUCTS = 10;

    // Pack structures as byte array (no padding)
    // Structure layout: [U8:1][I16LE:2][I32LE:4] = 7 bytes per struct
    std::vector<uint8_t> input(NUM_STRUCTS * 7);

    for (size_t i = 0; i < NUM_STRUCTS; i++) {
        size_t offset = i * 7;

        // Field 0: U8 (1 byte)
        uint8_t field0    = static_cast<uint8_t>(i * 10 + 1);
        input[offset + 0] = field0;

        // Field 1: I16LE (2 bytes, little-endian)
        int16_t field1    = static_cast<int16_t>(i * 100 + 42);
        input[offset + 1] = static_cast<uint8_t>(field1 & 0xFF);
        input[offset + 2] = static_cast<uint8_t>((field1 >> 8) & 0xFF);

        // Field 2: I32LE (4 bytes, little-endian)
        int32_t field2    = static_cast<int32_t>(i * 1000 + 12345);
        input[offset + 3] = static_cast<uint8_t>(field2 & 0xFF);
        input[offset + 4] = static_cast<uint8_t>((field2 >> 8) & 0xFF);
        input[offset + 5] = static_cast<uint8_t>((field2 >> 16) & 0xFF);
        input[offset + 6] = static_cast<uint8_t>((field2 >> 24) & 0xFF);
    }

    roundtrip_test(
            input.data(),
            input.size(),
            sddl2_parse_test_data::STRUCT_ARRAY_SEGMENT.data(),
            sddl2_parse_test_data::STRUCT_ARRAY_SEGMENT.size(),
            "StructureArraySegment");
}

TEST(SDDL2ReplayChunkTest, RoundTrip)
{
    std::array<uint8_t, 7> input = { 0x41, 0x42, 0x43, 0x34, 0x12, 0x78, 0x56 };
    std::array<SDDL2_ReplaySegment, 2> segments = {
        primitive_replay_segment(3, SDDL2_TYPE_BYTES, 3),
        primitive_replay_segment(4, SDDL2_TYPE_U16LE, 2),
    };

    replay_roundtrip_test(
            input.data(),
            input.size(),
            segments.data(),
            segments.size(),
            7,
            "ReplayChunkRoundTrip");
}

TEST(SDDL2ReplayChunkTest, RoundTripSlicedStructureChunk)
{
    std::array<SDDL2_Type, 3> const members = {
        primitive_type(SDDL2_TYPE_U8, 1),
        primitive_type(SDDL2_TYPE_I16LE, 1),
        primitive_type(SDDL2_TYPE_I32LE, 1),
    };
    SDDL2_Struct_data* const struct_data =
            create_structure_data(members.data(), members.size());

    // Mirror one middle chunk emitted from a larger structure segment: replay
    // only needs the chunk-local byte slice, its type metadata, and the
    // caller-supplied starting stream id.
    std::array<uint8_t, 28> const full_input = {
        0x11, 0x21, 0x22, 0x31, 0x32, 0x33, 0x34, 0x41, 0x51, 0x52,
        0x61, 0x62, 0x63, 0x64, 0x71, 0x81, 0x82, 0x91, 0x92, 0x93,
        0x94, 0xA1, 0xB1, 0xB2, 0xC1, 0xC2, 0xC3, 0xC4,
    };
    std::array<uint8_t, 14> input{};
    std::memcpy(input.data(), full_input.data() + 7, input.size());

    std::array<SDDL2_ReplaySegment, 1> const segments = {
        structure_replay_segment(input.size(), struct_data),
    };

    replay_roundtrip_test(
            input.data(),
            input.size(),
            segments.data(),
            segments.size(),
            3,
            "ReplayChunkSlicedStructureRoundTrip");

    free(struct_data);
}

TEST(SDDL2ReplayChunkTest, MissingSegmentsParamFails)
{
    std::array<uint8_t, 3> input = { 0x41, 0x42, 0x43 };
    std::vector<uint8_t> compressed(ZL_compressBound(input.size()));
    ZL_LocalParams const params = {};

    ReplayChunkCompressResult const result =
            compress_sddl2_replay_chunk_with_result(
                    compressed.data(),
                    compressed.size(),
                    input.data(),
                    input.size(),
                    &params);

    EXPECT_NE(ZL_isError(result.report), 0);
    EXPECT_NE(
            result.errorContext.find("requires a segments parameter"),
            std::string::npos);
}

TEST(SDDL2ReplayChunkTest, NegativeStartStreamIdFails)
{
    std::array<uint8_t, 3> input                = { 0x41, 0x42, 0x43 };
    std::array<SDDL2_ReplaySegment, 1> segments = { primitive_replay_segment(
            input.size(),
            SDDL2_TYPE_BYTES,
            static_cast<uint32_t>(input.size())) };
    std::vector<uint8_t> compressed(ZL_compressBound(input.size()));

    ZL_IntParam startStreamParam = {
        SDDL2_REPLAY_START_STREAM_ID_PARAM,
        -1,
    };
    ZL_RefParam replaySegmentsParam = {
        SDDL2_REPLAY_SEGMENTS_PARAM,
        segments.data(),
        segments.size() * sizeof(segments[0]),
    };
    ZL_LocalParams const params = {
        .intParams = { &startStreamParam, 1 },
        .refParams = { &replaySegmentsParam, 1 },
    };

    ReplayChunkCompressResult const result =
            compress_sddl2_replay_chunk_with_result(
                    compressed.data(),
                    compressed.size(),
                    input.data(),
                    input.size(),
                    &params);

    EXPECT_NE(ZL_isError(result.report), 0);
    EXPECT_NE(
            result.errorContext.find("must be non-negative"),
            std::string::npos);
}

TEST(SDDL2ReplayChunkTest, ZeroSegmentsPassthrough)
{
    std::array<uint8_t, 5> input = { 0x41, 0x42, 0x43, 0x44, 0x45 };

    replay_roundtrip_test(
            input.data(),
            input.size(),
            nullptr,
            0,
            0,
            "ReplayChunkZeroSegmentsPassthrough");
}

} // namespace
