# Copyright (c) Meta Platforms, Inc. and affiliates.

load("../../defs.bzl", "zs_cxxlibrary")

oncall("data_compression")

zs_cxxlibrary(
    name = "utils",
    srcs = [
        "compress_profiles.cpp",
        "util.cpp",
    ],
    headers = [
        "compress_profiles.h",
        "util.h",
    ],
    deps = [
        "../..:zstronglib",
        "../../cpp:openzl_cpp",
        "../../custom_parsers:custom_parsers",
        "../../custom_parsers:pytorch_model_parser",
        "../../custom_parsers/csv:csv_parser",
        "../../custom_parsers/parquet:parquet_graph",
        "../../custom_parsers/sddl:profile",
        "../../custom_parsers/shared_components:clustering",
        "../../tools:arg",
        "../../tools:io",
        "../../tools:logger",
        "../../tools/sddl/compiler:lib",
        "../../tools/sddl2/assembler:lib",
        "../../tools/sddl2/compiler:lib",
        "../../tools/training/ace:automated_compressor_explorer",
    ],
)
