// Copyright (c) Meta Platforms, Inc. and affiliates.

#ifndef OPENZL_CODECS_INTERLEAVE_COMMON_INTERLEAVE_H
#define OPENZL_CODECS_INTERLEAVE_COMMON_INTERLEAVE_H

#define ZL_INTERLEAVE_MAX_INPUTS 512

#endif // OPENZL_CODECS_INTERLEAVE_COMMON_INTERLEAVE_H
