load("../../defs.bzl", "zs_cxxlibrary")

oncall("data_compression")

zs_cxxlibrary(
    # @autodeps-skip
    name = "openzl_component",
    headers = ["OpenZLComponent.h"],
    exported_deps = [
        "../../cpp:openzl_cpp",
        "../datagen:datagen",
        ":openzl_input",
    ],
)

zs_cxxlibrary(
    # @autodeps-skip
    name = "openzl_input",
    srcs = ["OpenZLInput.cpp"],
    headers = ["OpenZLInput.h"],
    exported_deps = [
        "../../cpp:openzl_cpp",
    ],
)

zs_cxxlibrary(
    # @autodeps-skip
    name = "openzl_components",
    srcs = [
        "OpenZLComponents.cpp",
    ] + glob([
        "components/*.cpp",
    ]),
    headers = ["OpenZLComponents.h"],
    deps = [
        "../datagen:datagen",
        "fbsource//third-party/zstd:zstd",
    ],
    exported_deps = [
        ":openzl_component",
    ],
)
