# Copyright (c) Meta Platforms, Inc. and affiliates.

load("../../defs.bzl", "zs_cxxlibrary")

oncall("data_compression")

zs_cxxlibrary(
    name = "ml_selector_trainer",
    srcs = ["ml_selector_trainer.cpp"],
    headers = ["ml_selector_trainer.h"],
    compiler_flags = [
        "-Wno-unused-exception-parameter",  # For XGBoost warnings
    ],
    deps = [
        "../..:zstronglib",
        "../../cpp:openzl_cpp",
        "../../tests/datagen:datagen",  # @manual
        "../training:train_common",
        "../training/graph_mutation:graph_mutation",
        "../training/sample_collection:sample_collection",
        "../training/utils:training_utils",
        ":ml_features",
    ],
    exported_external_deps = [
        ("xgboost", None, "xgboost-cpp"),
        ("xgboost", None, "dmlc"),
    ],
)

zs_cxxlibrary(
    name = "ml_features",
    srcs = ["ml_features.cpp"],
    headers = ["ml_features.h"],
    deps = [
        "..:logger",
        "../..:zstronglib",
        "../../cpp:openzl_cpp",
        "../training/utils:training_utils",
    ],
)
