# Copyright (c) Meta Platforms, Inc. and affiliates.

load("../../../defs.bzl", "zs_unittest")

oncall("data_compression")

zs_unittest(
    name = "arg_parser_test",
    srcs = ["arg_parser_test.cpp"],
    deps = [
        "../..:arg",
    ],
)
