# Copyright (c) Meta Platforms, Inc. and affiliates.

load("@fbcode_macros//build_defs:cpp_binary.bzl", "cpp_binary")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("../../defs.bzl", "relative_headers")

oncall("data_compression")

cpp_library(
    # @autodeps-skip
    name = "tulip_v2",
    srcs = [
        "decode_tulip_v2.cpp",
        "encode_tulip_v2.cpp",
    ],
    headers = relative_headers([
        "decode_tulip_v2.h",
        "encode_tulip_v2.h",
    ]),
    header_namespace = "",
    exported_deps = [
        "../..:zstronglib",
        "../thrift/kernels:decode_thrift_binding",
        "../thrift/kernels:encode_thrift_binding",
        "//folly:range",
        "//folly:scope_guard",
        "//folly/io:iobuf",
        "//thrift/lib/cpp2/protocol:protocol",
    ],
)

cpp_binary(
    # @autodeps-skip
    name = "main",
    srcs = ["main.cpp"],
    deps = [
        "../..:zstronglib",
        "../../tools:zstrong_cpp",
        ":tulip_v2",
        "//folly:file_util",
        "//folly/init:init",
    ],
)
