# Copyright (c) Meta Platforms, Inc. and affiliates.

load("@fbcode_macros//build_defs:cpp_binary.bzl", "cpp_binary")

oncall("data_compression")

cpp_binary(
    name = "experiment_2025",
    srcs = [
        "runner.cpp",
    ],
)

cpp_binary(
    name = "experiment_analysis",
    srcs = [
        "analysis.cpp",
    ],
)
