# Copyright (c) Meta Platforms, Inc. and affiliates.

# @noautodeps

load("@fbcode_macros//build_defs:cpp_binary.bzl", "cpp_binary")

oncall("data_compression")

cpp_binary(
    name = "compress",
    srcs = ["compress.cpp"],
    deps = [
        "..:zstronglib",
        "../tools:zstrong_json",
        "//folly:file_util",
    ],
)

cpp_binary(
    name = "dump_transform_inputs",
    srcs = ["dump_transform_inputs.cpp"],
    deps = [
        "..:zstronglib",
    ],
)
