language: c

matrix:
  include:
    - name: "linux-ppc64le-gcc-9"
      os: linux
      dist: bionic
      arch: ppc64le
      compiler: gcc-9
      env:
        - CXX="g++-9"
        - PKG_CC="gcc-9 g++-9"
    - name: "linux-ppc64le-gcc-10"
      os: linux
      dist: bionic
      arch: ppc64le
      compiler: gcc-10
      env:
        - CXX="g++-10"
        - PKG_CC="gcc-10 g++-10"
    - name: "linux-ppc64le-gcc-11"
      os: linux
      dist: focal
      arch: ppc64le
      compiler: gcc-11
      env:
        - CXX="g++-11"
        - PKG_CC="gcc-11 g++-11"

before_install:
  - sudo add-apt-repository universe
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - travis_wait 5 sudo apt-get -y install ${PKG_CC} doxygen graphviz

script:
  - mkdir $(pwd)/install
  - ./configure --prefix=$(pwd)/install
  - make -j$(nproc)
  - make -j$(nproc) -C test build-TESTS
  - make -j$(nproc) bench
  - make -j$(nproc) -C selftest all
  - make -j$(nproc) install
