# Copyright (c) Meta Platforms, Inc. and affiliates.

load("../../defs.bzl", "zs_library")

oncall("data_compression")

zs_library(
    name = "profile",
    srcs = glob([
        "*.c",
        "*.cpp",
    ]),
    headers = glob([
        "*.h",
    ]),
    deps = [
        "../../tools/sddl/compiler:lib",
        "../shared_components:clustering",
    ],
    exported_deps = [
        "../..:zstronglib",
    ],
)
