# Copyright (c) Meta Platforms, Inc. and affiliates.

load("@fbcode_macros//build_defs:python_binary.bzl", "python_binary")
load("@fbcode_macros//build_defs:python_library.bzl", "python_library")

oncall("data_compression")

python_binary(
    name = "tradeoff-plots",
    srcs = ["tradeoff-plots.py"],
    base_module = "",
    labels = ["autodeps2_generated"],
    main_function = "tradeoff-plots.main",
    deps = [
        "fbsource//third-party/pypi/kaleido:kaleido",  # @manual
        "fbsource//third-party/pypi/pandas:pandas",
        "fbsource//third-party/pypi/plotly:plotly",
    ],
)

python_library(
    name = "make-pareto-optimal-figures",
    srcs = ["make-pareto-optimal-figures.py"],
    labels = ["autodeps2_generated"],
)
