# Copyright (c) Meta Platforms, Inc. and affiliates.

name: Wheels

on:
  workflow_dispatch:

  # Only run on PRs that either touch the Python bindings or the CMake build system.
  # This is an expensive workflow that almost always passes when Python isn't modified,
  # so only run it when it's needed. The tests will still be run on commit for everything.
  pull_request:
    paths:
      - 'py/**'
      - 'CMakeLists.txt'
      - 'build-scripts/**'
      - '.github/workflows/wheels.yml'

  # Always run on commit to dev branch to ensure the test is consistently run.
  # There are far fewer commits than PR versions, so this is relatively cheap.
  push:
    branches:
      - dev

  release:
    types:
      - published


jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build SDist
      run: pipx run build --sdist py

    - name: Check metadata
      run: pipx run twine check py/dist/*

    - uses: actions/upload-artifact@v4
      with:
        name: dist-sdist
        path: py/dist/*.tar.gz


  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Once MSVC is supported we can build Windows packages as well by adding windows-latest
        # Once we're public we can build on ubuntu-24.04-arm & windows-11-arm.
        # They are not supported for private repos.
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: pypa/cibuildwheel@v3.0.0
      with:
        package-dir: py

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        path: wheelhouse/*.whl
        name: dist-${{ matrix.os }}

  # This can be uncommented to support automatic uploads to PyPI on release
  # once OpenZL is publicly available.
  upload_all:
    name: Upload if release
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
    - uses: actions/setup-python@v5
    - uses: actions/download-artifact@v4
      with:
        path: dist
        pattern: dist-*
        merge-multiple: true

    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
