// Copyright (c) Meta Platforms, Inc. and affiliates.

#ifndef OPENZL_SDDL2_INTERPRETER_H
#define OPENZL_SDDL2_INTERPRETER_H

#include <stddef.h>
#include <stdint.h>
#include "openzl/compress/graphs/sddl2/sddl2_vm.h"

#if defined(__cplusplus)
extern "C" {
#endif

/**
 * OpenZL VM Bytecode Interpreter
 *
 * Executes bytecode programs generated by the SDDL assembler.
 *
 * Bytecode Format:
 * - Instructions are 32-bit words (little-endian)
 * - Format: [Family:16bit][Opcode:16bit]
 * - Some instructions have immediate operands following the instruction word
 */

/**
 * Execute a bytecode program.
 *
 * @param bytecode Pointer to bytecode buffer
 * @param bytecode_size Size of bytecode in bytes (must be multiple of 4)
 * @param input_data Pointer to input data buffer
 * @param input_size Size of input data in bytes
 * @param output_segments Pointer to segment list to populate (must be
 * initialized)
 *
 * @return SDDL2_OK on success, error code on failure
 */
SDDL2_Error SDDL2_execute_bytecode(
        const void* bytecode,
        size_t bytecode_size,
        const void* input_data,
        size_t input_size,
        SDDL2_Segment_list* output_segments);

#if defined(__cplusplus)
} // extern "C"
#endif

#endif // OPENZL_SDDL2_INTERPRETER_H
