# Copyright (c) Meta Platforms, Inc. and affiliates.

load("../../../defs.bzl", "zs_unittest")

oncall("data_compression")

zs_unittest(
    name = "test_mlSelectorTrainer",
    srcs = ["test_mlSelectorTrainer.cpp"],
    deps = [
        "..:ml_features",
        "..:ml_selector_trainer",
        "../../../tests:ml_selector_utils",
        "../../../tests:utils",
        "../../../tests/datagen:datagen",
        "../../training:train",
        "fbsource//third-party/googletest:gtest",
    ],
)

zs_unittest(
    # @autodeps-skip
    name = "test_mlSelectorGraph",
    srcs = ["test_mlSelectorGraph.cpp"],
    deps = [
        "../../..:zstronglib",
        "../../../cpp:openzl_cpp",
        "../../../tests:ml_selector_utils",
        "../../../tests:utils",
        "../../../tests/datagen:datagen",
    ],
)
